### PR TITLE
Some improvements 

### PR DESCRIPTION
**Pull request by slayer**

### CODE REVIEW

**Comment by firstrow** [comment]
Thanks for the PR. I will merge after test.

**Comment by slayer** [comment]
There is some problem with `go get`. 
WIth `require "github.com/firstrow/logvoyage/..."`  I cant develop and push to github.
With local require:  `requre "../commands" ` there are problems with CI and initial building.

**Comment by firstrow** [comment]
I think it good convention always to use full paths.

**Comment by slayer** [comment]
Maybe, but not for team work :(

**Comment by firstrow** [comment]
Why not good for team? As I see almost 99% uses full path.

**Comment by bweston92** [comment]
I agree with @firstrow using full paths makes it easier. If you don't want it in your gopath then just symbolic link it to your development directory. How-ever there are some other improvements that are interesting in this PR especially docker as I just discovered this project and first thoughts was where is the docker package.

**Comment by firstrow** [comment]
@slayer: it would be nice if you remove raltive paths, so I can merge this one.

**Comment by slayer** [comment]
@firstrow ok

**Comment by firstrow** [comment]
thanks for contributing to project. project is no longer maintained. v2 will be out soon.
check http://github.com/logvoyage for updates. thanks.

**Comment by slayer** [comment]
Cool. Will be waiting.

**Comment by firstrow** [comment]
https://github.com/logvoyage/logvoyage 
sorry, no docs for now, setup is easy, you can write me on irc/gitter if you are interested in contributions on this early stage.

**Comment by firstrow** [comment]
@slayer

**Pull request closed without merging**
